// Station data verified from Wikipedia EN and AsiaWaves.net.
// Stations are split into per-city lists so adding more frequencies later is easy:
// just append to the relevant city list and re-run analyze — no other file changes.
//
// Coverage status:
//   Jakarta      FM 87.6–107.7  COMPLETE     AM complete
//   Surabaya     FM 87.7–107.7  COMPLETE     AM complete
//   Semarang     FM 87.8–107.9  COMPLETE     AM complete
//   Bandung      FM 87.7–107.5  COMPLETE     AM complete
//   Yogyakarta   FM 87.9–107.2  COMPLETE     AM complete
//   Medan        FM 88.0–106.6  COMPLETE     AM complete
//   Makassar, Bali, Solo, Malang — NOT YET VERIFIED

import 'frequencies.dart';

class LocalStation {
  final String name;
  final double frequency; // MHz for FM, kHz for AM
  final String city;
  final String genre;
  final Band band;

  const LocalStation({
    required this.name,
    required this.frequency,
    required this.city,
    required this.genre,
    required this.band,
  });

  double? get fmFrequency => band == Band.fm ? frequency : null;
  int? get amFrequency => band == Band.am ? frequency.toInt() : null;
}

// ── JAKARTA ─────────────────────────────────────────────────────────────────
// Source: Wikipedia EN (March 2026) — COMPLETE
const _jakarta = [
  LocalStation(
    name: 'The Rockin Life',
    frequency: 87.6,
    city: 'Jakarta',
    genre: 'hot_ac',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Mustang 88 FM',
    frequency: 88.0,
    city: 'Jakarta',
    genre: 'top40',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Global Radio',
    frequency: 88.4,
    city: 'Jakarta',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'RRI Programa 3',
    frequency: 88.8,
    city: 'Jakarta',
    genre: 'news',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Campursari FM',
    frequency: 89.2,
    city: 'Jakarta',
    genre: 'dangdut',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Publica FM',
    frequency: 89.6,
    city: 'Jakarta',
    genre: 'hot_ac',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Elshinta',
    frequency: 90.0,
    city: 'Jakarta',
    genre: 'news',
    band: Band.fm,
  ),
  LocalStation(
    name: 'VOKS Radio',
    frequency: 90.4,
    city: 'Jakarta',
    genre: 'hot_ac',
    band: Band.fm,
  ),
  LocalStation(
    name: 'OZ Radio',
    frequency: 90.8,
    city: 'Jakarta',
    genre: 'hot_ac',
    band: Band.fm,
  ),
  LocalStation(
    name: 'RRI Programa 1',
    frequency: 91.2,
    city: 'Jakarta',
    genre: 'news',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Indika FM',
    frequency: 91.6,
    city: 'Jakarta',
    genre: 'hot_ac',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Sonora',
    frequency: 92.0,
    city: 'Jakarta',
    genre: 'news',
    band: Band.fm,
  ),
  LocalStation(
    name: 'PAS FM',
    frequency: 92.4,
    city: 'Jakarta',
    genre: 'business',
    band: Band.fm,
  ),
  LocalStation(
    name: 'RRI Programa 4',
    frequency: 92.8,
    city: 'Jakarta',
    genre: 'culture',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Hot FM',
    frequency: 93.2,
    city: 'Jakarta',
    genre: 'dangdut',
    band: Band.fm,
  ),
  LocalStation(
    name: 'KISI FM',
    frequency: 93.4,
    city: 'Jakarta',
    genre: 'top40',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Mersi FM',
    frequency: 93.9,
    city: 'Jakarta',
    genre: 'dangdut',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Good Radio',
    frequency: 94.3,
    city: 'Jakarta',
    genre: 'top40',
    band: Band.fm,
  ),
  LocalStation(
    name: 'MG Radio',
    frequency: 94.7,
    city: 'Jakarta',
    genre: 'news',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Kis FM',
    frequency: 95.1,
    city: 'Jakarta',
    genre: 'hot_ac',
    band: Band.fm,
  ),
  LocalStation(
    name: 'RASfm',
    frequency: 95.5,
    city: 'Jakarta',
    genre: 'religious',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Smart FM',
    frequency: 95.9,
    city: 'Jakarta',
    genre: 'business',
    band: Band.fm,
  ),
  LocalStation(
    name: 'RPK FM',
    frequency: 96.3,
    city: 'Jakarta',
    genre: 'religious',
    band: Band.fm,
  ),
  LocalStation(
    name: 'IMI Radio',
    frequency: 96.7,
    city: 'Jakarta',
    genre: 'classic_hits',
    band: Band.fm,
  ),
  LocalStation(
    name: 'RDI',
    frequency: 97.1,
    city: 'Jakarta',
    genre: 'dangdut',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Motion Radio',
    frequency: 97.5,
    city: 'Jakarta',
    genre: 'top40',
    band: Band.fm,
  ),
  LocalStation(
    name: 'FeMale Radio',
    frequency: 97.9,
    city: 'Jakarta',
    genre: 'hot_ac',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Mandarin Station',
    frequency: 98.3,
    city: 'Jakarta',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Gen FM',
    frequency: 98.7,
    city: 'Jakarta',
    genre: 'top40',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Delta FM',
    frequency: 99.1,
    city: 'Jakarta',
    genre: 'hot_ac',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Smooth FM',
    frequency: 99.5,
    city: 'Jakarta',
    genre: 'hot_ac',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Z FM',
    frequency: 99.9,
    city: 'Jakarta',
    genre: 'hot_ac',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Megaswara FM',
    frequency: 100.8,
    city: 'Jakarta',
    genre: 'hot_ac',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Jak FM',
    frequency: 101.0,
    city: 'Jakarta',
    genre: 'hot_ac',
    band: Band.fm,
  ),
  LocalStation(
    name: 'I-Swara',
    frequency: 101.4,
    city: 'Jakarta',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Prambors FM',
    frequency: 102.2,
    city: 'Jakarta',
    genre: 'top40',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Camajaya FM',
    frequency: 102.6,
    city: 'Jakarta',
    genre: 'classic_hits',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Pop FM',
    frequency: 103.0,
    city: 'Jakarta',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'DFM',
    frequency: 103.4,
    city: 'Jakarta',
    genre: 'dangdut',
    band: Band.fm,
  ),
  LocalStation(
    name: 'X Channel',
    frequency: 103.8,
    city: 'Jakarta',
    genre: 'rock',
    band: Band.fm,
  ),
  LocalStation(
    name: 'MS Tri FM',
    frequency: 104.2,
    city: 'Jakarta',
    genre: 'top40',
    band: Band.fm,
  ),
  LocalStation(
    name: 'MNC Trijaya FM',
    frequency: 104.6,
    city: 'Jakarta',
    genre: 'news',
    band: Band.fm,
  ),
  LocalStation(
    name: 'RRI Programa 2',
    frequency: 105.0,
    city: 'Jakarta',
    genre: 'hot_ac',
    band: Band.fm,
  ),
  LocalStation(
    name: 'CBB FM',
    frequency: 105.4,
    city: 'Jakarta',
    genre: 'dangdut',
    band: Band.fm,
  ),
  LocalStation(
    name: 'MOST Radio',
    frequency: 105.8,
    city: 'Jakarta',
    genre: 'classic_hits',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Bens Radio',
    frequency: 106.2,
    city: 'Jakarta',
    genre: 'dangdut',
    band: Band.fm,
  ),
  LocalStation(
    name: 'V Radio',
    frequency: 106.6,
    city: 'Jakarta',
    genre: 'top40',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Media Dangdut Radio',
    frequency: 107.1,
    city: 'Jakarta',
    genre: 'dangdut',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Mandala Muda Radio',
    frequency: 107.7,
    city: 'Jakarta',
    genre: 'top40',
    band: Band.fm,
  ),
  // AM — 531 & 567 kHz below dial min (600), 1602 above dial max (1600): search-only
  LocalStation(
    name: 'Kabar Inklusif',
    frequency: 531,
    city: 'Jakarta',
    genre: 'news',
    band: Band.am,
  ),
  LocalStation(
    name: 'Trax Jakarta',
    frequency: 567,
    city: 'Jakarta',
    genre: 'pop',
    band: Band.am,
  ),
  LocalStation(
    name: 'Radio Samhan',
    frequency: 630,
    city: 'Jakarta',
    genre: 'talk',
    band: Band.am,
  ),
  LocalStation(
    name: 'Radio Nam Nam Nam',
    frequency: 666,
    city: 'Jakarta',
    genre: 'talk',
    band: Band.am,
  ),
  LocalStation(
    name: 'Radio Muara',
    frequency: 693,
    city: 'Jakarta',
    genre: 'talk',
    band: Band.am,
  ),
  LocalStation(
    name: 'Radio Bharata',
    frequency: 738,
    city: 'Jakarta',
    genre: 'talk',
    band: Band.am,
  ),
  LocalStation(
    name: 'Radio Rodja',
    frequency: 756,
    city: 'Jakarta',
    genre: 'religious',
    band: Band.am,
  ),
  LocalStation(
    name: 'Buana Komunika',
    frequency: 810,
    city: 'Jakarta',
    genre: 'talk',
    band: Band.am,
  ),
  LocalStation(
    name: 'Radio Berita Klasik',
    frequency: 828,
    city: 'Jakarta',
    genre: 'news',
    band: Band.am,
  ),
  LocalStation(
    name: 'Persada Radio',
    frequency: 1008,
    city: 'Jakarta',
    genre: 'talk',
    band: Band.am,
  ),
  LocalStation(
    name: 'Suara Khatulistiwa',
    frequency: 1026,
    city: 'Jakarta',
    genre: 'talk',
    band: Band.am,
  ),
  LocalStation(
    name: 'Radio Cendrawasih',
    frequency: 1062,
    city: 'Jakarta',
    genre: 'talk',
    band: Band.am,
  ),
  LocalStation(
    name: 'Radio UNTAR',
    frequency: 1098,
    city: 'Jakarta',
    genre: 'education',
    band: Band.am,
  ),
  LocalStation(
    name: 'Radio Safari',
    frequency: 1134,
    city: 'Jakarta',
    genre: 'talk',
    band: Band.am,
  ),
  LocalStation(
    name: 'Radio JJM',
    frequency: 1170,
    city: 'Jakarta',
    genre: 'talk',
    band: Band.am,
  ),
  LocalStation(
    name: 'IRS Radio',
    frequency: 1224,
    city: 'Jakarta',
    genre: 'talk',
    band: Band.am,
  ),
  LocalStation(
    name: 'Radio Rona MKB',
    frequency: 1440,
    city: 'Jakarta',
    genre: 'talk',
    band: Band.am,
  ),
  LocalStation(
    name: 'Radio Angkatan Bersenjata',
    frequency: 1494,
    city: 'Jakarta',
    genre: 'news',
    band: Band.am,
  ),
  LocalStation(
    name: 'Radio Masjid Sunda Kelapa',
    frequency: 1530,
    city: 'Jakarta',
    genre: 'religious',
    band: Band.am,
  ),
  LocalStation(
    name: 'Hidupin Radio Network',
    frequency: 1602,
    city: 'Jakarta',
    genre: 'talk',
    band: Band.am,
  ),
];

// ── SURABAYA ─────────────────────────────────────────────────────────────────
// Source: AsiaWaves.net (Nov 2025) — FM partial to 95.2 MHz
const _surabaya = [
  LocalStation(
    name: 'Voks Radio',
    frequency: 87.7,
    city: 'Surabaya',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Kota FM',
    frequency: 88.1,
    city: 'Surabaya',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Metro FM',
    frequency: 88.5,
    city: 'Surabaya',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Smart FM Surabaya',
    frequency: 88.9,
    city: 'Surabaya',
    genre: 'news',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Prambors Surabaya',
    frequency: 89.3,
    city: 'Surabaya',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'iSwara FM Surabaya',
    frequency: 89.7,
    city: 'Surabaya',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Media FM',
    frequency: 90.1,
    city: 'Surabaya',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Ampel Denta',
    frequency: 90.5,
    city: 'Surabaya',
    genre: 'religious',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Global FM Surabaya',
    frequency: 90.9,
    city: 'Surabaya',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Suzana FM',
    frequency: 91.3,
    city: 'Surabaya',
    genre: 'dangdut',
    band: Band.fm,
  ),
  LocalStation(
    name: 'RRI Surabaya Ch 5',
    frequency: 91.7,
    city: 'Surabaya',
    genre: 'music',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio BFM',
    frequency: 92.9,
    city: 'Surabaya',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'El Victor FM',
    frequency: 93.3,
    city: 'Surabaya',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Suara Muslim',
    frequency: 93.8,
    city: 'Surabaya',
    genre: 'religious',
    band: Band.fm,
  ),
  LocalStation(
    name: 'DJ FM',
    frequency: 94.8,
    city: 'Surabaya',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'RRI Pro 2 Surabaya',
    frequency: 95.2,
    city: 'Surabaya',
    genre: 'music',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio TOC FM',
    frequency: 95.6,
    city: 'Surabaya',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Mercury',
    frequency: 96.0,
    city: 'Surabaya',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Bahtera Yudha',
    frequency: 96.4,
    city: 'Surabaya',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'RRI Pro 4 Surabaya',
    frequency: 96.8,
    city: 'Surabaya',
    genre: 'culture',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Elshinta Surabaya',
    frequency: 97.6,
    city: 'Surabaya',
    genre: 'news',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Sonora Surabaya',
    frequency: 98.0,
    city: 'Surabaya',
    genre: 'classic_hits',
    band: Band.fm,
  ),
  LocalStation(
    name: 'M Radio Surabaya',
    frequency: 98.8,
    city: 'Surabaya',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'RRI Pro 1 Surabaya',
    frequency: 99.2,
    city: 'Surabaya',
    genre: 'news',
    band: Band.fm,
  ),
  LocalStation(
    name: 'She Radio',
    frequency: 99.6,
    city: 'Surabaya',
    genre: 'hot_ac',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Suara Surabaya',
    frequency: 100.0,
    city: 'Surabaya',
    genre: 'news',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Klik FM',
    frequency: 100.5,
    city: 'Surabaya',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Istara FM',
    frequency: 101.1,
    city: 'Surabaya',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Cakrawala FM',
    frequency: 101.5,
    city: 'Surabaya',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Strato FM',
    frequency: 101.9,
    city: 'Surabaya',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'X Channel Surabaya',
    frequency: 102.3,
    city: 'Surabaya',
    genre: 'rock',
    band: Band.fm,
  ),
  LocalStation(
    name: 'MTB FM',
    frequency: 102.7,
    city: 'Surabaya',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Gen FM Surabaya',
    frequency: 103.1,
    city: 'Surabaya',
    genre: 'top40',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Wijaya FM',
    frequency: 103.5,
    city: 'Surabaya',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Prima Radio',
    frequency: 103.8,
    city: 'Surabaya',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'PAS FM Surabaya',
    frequency: 104.3,
    city: 'Surabaya',
    genre: 'religious',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Trijaya FM Surabaya',
    frequency: 104.7,
    city: 'Surabaya',
    genre: 'news',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio JJ FM',
    frequency: 105.1,
    city: 'Surabaya',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'EBS FM',
    frequency: 105.9,
    city: 'Surabaya',
    genre: 'education',
    band: Band.fm,
  ),
  LocalStation(
    name: 'RRI Pro 6 Surabaya',
    frequency: 106.3,
    city: 'Surabaya',
    genre: 'music',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Merdeka FM',
    frequency: 106.7,
    city: 'Surabaya',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'RRI Pro 3 Surabaya',
    frequency: 107.5,
    city: 'Surabaya',
    genre: 'news',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio CMC FM',
    frequency: 107.7,
    city: 'Surabaya',
    genre: 'pop',
    band: Band.fm,
  ),
  // AM — 585 kHz below dial min (600): search-only
  LocalStation(
    name: 'RRI Surabaya Pro 4',
    frequency: 585,
    city: 'Surabaya',
    genre: 'news',
    band: Band.am,
  ),
  LocalStation(
    name: 'Radio Suara al Iman',
    frequency: 918,
    city: 'Surabaya',
    genre: 'religious',
    band: Band.am,
  ),
  LocalStation(
    name: 'RRI Surabaya Pro 3',
    frequency: 999,
    city: 'Surabaya',
    genre: 'news',
    band: Band.am,
  ),
  LocalStation(
    name: 'Radio Yasmara',
    frequency: 1152,
    city: 'Surabaya',
    genre: 'talk',
    band: Band.am,
  ),
];

// ── SEMARANG ─────────────────────────────────────────────────────────────────
// Source: AsiaWaves.net — FM partial to 96.1 MHz
const _semarang = [
  LocalStation(
    name: 'Radio Gaul',
    frequency: 87.8,
    city: 'Semarang',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'RRI Semarang Pro 4',
    frequency: 88.2,
    city: 'Semarang',
    genre: 'culture',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Rhema FM',
    frequency: 88.6,
    city: 'Semarang',
    genre: 'religious',
    band: Band.fm,
  ),
  LocalStation(
    name: 'RRI Semarang Pro 1',
    frequency: 89.0,
    city: 'Semarang',
    genre: 'news',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Maneuver Radio',
    frequency: 89.4,
    city: 'Semarang',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Trijaya FM Semarang',
    frequency: 89.8,
    city: 'Semarang',
    genre: 'news',
    band: Band.fm,
  ),
  LocalStation(
    name: 'iSwara FM Semarang',
    frequency: 90.2,
    city: 'Semarang',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Elshinta Semarang',
    frequency: 91.0,
    city: 'Semarang',
    genre: 'news',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Dangdut Indonesia Semarang',
    frequency: 91.8,
    city: 'Semarang',
    genre: 'dangdut',
    band: Band.fm,
  ),
  LocalStation(
    name: 'RRI Semarang Pro 3',
    frequency: 92.2,
    city: 'Semarang',
    genre: 'music',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Idola FM',
    frequency: 92.6,
    city: 'Semarang',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'C Radio',
    frequency: 93.4,
    city: 'Semarang',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Agape FM',
    frequency: 94.5,
    city: 'Semarang',
    genre: 'religious',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Good News FM',
    frequency: 94.9,
    city: 'Semarang',
    genre: 'religious',
    band: Band.fm,
  ),
  LocalStation(
    name: 'RRI Semarang Pro 2',
    frequency: 95.3,
    city: 'Semarang',
    genre: 'music',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Fit Radio',
    frequency: 95.7,
    city: 'Semarang',
    genre: 'sports',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Delta FM Semarang',
    frequency: 96.1,
    city: 'Semarang',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Ichthus Radio',
    frequency: 96.5,
    city: 'Semarang',
    genre: 'religious',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Suara Semarang',
    frequency: 96.9,
    city: 'Semarang',
    genre: 'news',
    band: Band.fm,
  ),
  LocalStation(
    name: 'ProAlma FM',
    frequency: 97.7,
    city: 'Semarang',
    genre: 'education',
    band: Band.fm,
  ),
  LocalStation(
    name: 'UP Radio',
    frequency: 98.5,
    city: 'Semarang',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Sonora Semarang',
    frequency: 98.9,
    city: 'Semarang',
    genre: 'classic_hits',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radiks Best FM',
    frequency: 99.3,
    city: 'Semarang',
    genre: 'top40',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Rasika',
    frequency: 100.1,
    city: 'Semarang',
    genre: 'dangdut',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Suara Diponegoro',
    frequency: 100.6,
    city: 'Semarang',
    genre: 'education',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio RCTFM',
    frequency: 101.2,
    city: 'Semarang',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'IBC FM',
    frequency: 101.6,
    city: 'Semarang',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Prambors Semarang',
    frequency: 102.0,
    city: 'Semarang',
    genre: 'top40',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Gajah Mada FM',
    frequency: 102.4,
    city: 'Semarang',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio J FM',
    frequency: 102.8,
    city: 'Semarang',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio KIS FM Semarang',
    frequency: 103.2,
    city: 'Semarang',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio POP FM Semarang',
    frequency: 103.6,
    city: 'Semarang',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Imelda FM',
    frequency: 104.4,
    city: 'Semarang',
    genre: 'hot_ac',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio SSFM',
    frequency: 105.2,
    city: 'Semarang',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Rasika FM',
    frequency: 105.6,
    city: 'Semarang',
    genre: 'dangdut',
    band: Band.fm,
  ),
  LocalStation(
    name: 'PAS FM Semarang',
    frequency: 106.0,
    city: 'Semarang',
    genre: 'business',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio SPS FM',
    frequency: 106.6,
    city: 'Semarang',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Thomson Semarang',
    frequency: 106.8,
    city: 'Semarang',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Suara Serasi',
    frequency: 107.3,
    city: 'Semarang',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio DAIS FM',
    frequency: 107.9,
    city: 'Semarang',
    genre: 'religious',
    band: Band.fm,
  ),
  LocalStation(
    name: 'RRI Semarang Pro 4 AM',
    frequency: 801,
    city: 'Semarang',
    genre: 'news',
    band: Band.am,
  ),
  LocalStation(
    name: 'Radio Mutiara Quran',
    frequency: 1170,
    city: 'Semarang',
    genre: 'religious',
    band: Band.am,
  ),
];

// ── BANDUNG ──────────────────────────────────────────────────────────────────
// Source: AsiaWaves.net — FM partial to 93.7 MHz
// Excluded: 540 kHz AM (RRI Bandung Pro-4, off air Nov 2025)
const _bandung = [
  LocalStation(
    name: 'The Rockin Life Bandung',
    frequency: 87.7,
    city: 'Bandung',
    genre: 'hot_ac',
    band: Band.fm,
  ),
  LocalStation(
    name: 'StudioEast Radio',
    frequency: 88.1,
    city: 'Bandung',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'RRI Bandung Pro 3',
    frequency: 88.5,
    city: 'Bandung',
    genre: 'news',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Auto Radio',
    frequency: 88.9,
    city: 'Bandung',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Elshinta Bandung',
    frequency: 89.3,
    city: 'Bandung',
    genre: 'news',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Okezone Radio Bandung',
    frequency: 89.7,
    city: 'Bandung',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Zora',
    frequency: 90.1,
    city: 'Bandung',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Cakra FM',
    frequency: 90.5,
    city: 'Bandung',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'X-Channel Bandung',
    frequency: 90.9,
    city: 'Bandung',
    genre: 'rock',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Trijaya FM Bandung',
    frequency: 91.3,
    city: 'Bandung',
    genre: 'news',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Voks Radio Bandung',
    frequency: 91.7,
    city: 'Bandung',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Mei Sheng',
    frequency: 92.1,
    city: 'Bandung',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Maestro FM',
    frequency: 92.5,
    city: 'Bandung',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Sonora Bandung',
    frequency: 93.3,
    city: 'Bandung',
    genre: 'news',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Paramuda',
    frequency: 93.7,
    city: 'Bandung',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Delta FM Bandung',
    frequency: 94.4,
    city: 'Bandung',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Fit Radio Bandung',
    frequency: 94.8,
    city: 'Bandung',
    genre: 'sports',
    band: Band.fm,
  ),
  LocalStation(
    name: 'B-Radio',
    frequency: 95.6,
    city: 'Bandung',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'RRI Pro 2 Bandung',
    frequency: 96.0,
    city: 'Bandung',
    genre: 'music',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Kencana FM',
    frequency: 96.8,
    city: 'Bandung',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'NewShinta FM',
    frequency: 97.2,
    city: 'Bandung',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'RRI Pro 1 Bandung',
    frequency: 97.6,
    city: 'Bandung',
    genre: 'news',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Prambors Bandung',
    frequency: 98.4,
    city: 'Bandung',
    genre: 'top40',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Raka FM',
    frequency: 98.8,
    city: 'Bandung',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Play 99ers',
    frequency: 100.0,
    city: 'Bandung',
    genre: 'top40',
    band: Band.fm,
  ),
  LocalStation(
    name: 'KLCBS Jazz Bandung',
    frequency: 100.4,
    city: 'Bandung',
    genre: 'classic_hits',
    band: Band.fm,
  ),
  LocalStation(
    name: 'MGT Radio',
    frequency: 101.1,
    city: 'Bandung',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Dahlia FM',
    frequency: 101.5,
    city: 'Bandung',
    genre: 'dangdut',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Cosmo Radio',
    frequency: 101.9,
    city: 'Bandung',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Rase FM',
    frequency: 102.3,
    city: 'Bandung',
    genre: 'hot_ac',
    band: Band.fm,
  ),
  LocalStation(
    name: 'MQ FM Bandung',
    frequency: 102.7,
    city: 'Bandung',
    genre: 'religious',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Chevy FM',
    frequency: 103.5,
    city: 'Bandung',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Hits Unikom Radio',
    frequency: 103.9,
    city: 'Bandung',
    genre: 'top40',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Rodja Bandung',
    frequency: 104.3,
    city: 'Bandung',
    genre: 'religious',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Rama FM',
    frequency: 104.7,
    city: 'Bandung',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'iSwara FM Bandung',
    frequency: 105.1,
    city: 'Bandung',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Garuda Radio Visual',
    frequency: 105.5,
    city: 'Bandung',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Ardan Radio',
    frequency: 105.9,
    city: 'Bandung',
    genre: 'top40',
    band: Band.fm,
  ),
  LocalStation(
    name: 'MARA FM',
    frequency: 106.7,
    city: 'Bandung',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'K-Lite FM',
    frequency: 107.1,
    city: 'Bandung',
    genre: 'classic_hits',
    band: Band.fm,
  ),
  LocalStation(
    name: 'PRFM',
    frequency: 107.5,
    city: 'Bandung',
    genre: 'news',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Barani',
    frequency: 1116,
    city: 'Bandung',
    genre: 'education',
    band: Band.am,
  ),
  LocalStation(
    name: 'Radio Rodja Bandung',
    frequency: 1476,
    city: 'Bandung',
    genre: 'religious',
    band: Band.am,
  ),
];

// ── YOGYAKARTA ───────────────────────────────────────────────────────────────
// Source: AsiaWaves.net — FM partial to 95.8 MHz
// Excluded AM: 1062 (Radio Bin Baz, off air), 1179 (Radio Unisia, off air)
const _yogyakarta = [
  LocalStation(
    name: 'Radio Dangdut Indonesia Yogya',
    frequency: 87.9,
    city: 'Yogyakarta',
    genre: 'dangdut',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Q',
    frequency: 88.3,
    city: 'Yogyakarta',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'iSwara FM Yogya',
    frequency: 88.7,
    city: 'Yogyakarta',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Pesona Bara FM',
    frequency: 89.1,
    city: 'Yogyakarta',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'JIZ FM',
    frequency: 89.5,
    city: 'Yogyakarta',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Sasando FM',
    frequency: 90.3,
    city: 'Yogyakarta',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'UTY FM',
    frequency: 90.7,
    city: 'Yogyakarta',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'RRI Yogyakarta Pro 1',
    frequency: 91.1,
    city: 'Yogyakarta',
    genre: 'news',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Thomson Jogja',
    frequency: 91.9,
    city: 'Yogyakarta',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio MQ FM',
    frequency: 92.3,
    city: 'Yogyakarta',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'MBS FM',
    frequency: 92.7,
    city: 'Yogyakarta',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Argososro',
    frequency: 93.2,
    city: 'Yogyakarta',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Megaswara FM Jogja',
    frequency: 93.8,
    city: 'Yogyakarta',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Persatuan',
    frequency: 94.2,
    city: 'Yogyakarta',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Kota Perak FM',
    frequency: 94.6,
    city: 'Yogyakarta',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Masdha FM',
    frequency: 95.0,
    city: 'Yogyakarta',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Yasika FM',
    frequency: 95.4,
    city: 'Yogyakarta',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Prambors Yogyakarta',
    frequency: 95.8,
    city: 'Yogyakarta',
    genre: 'top40',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Istakalisa FM',
    frequency: 96.2,
    city: 'Yogyakarta',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'MNC Trijaya FM Yogya',
    frequency: 97.0,
    city: 'Yogyakarta',
    genre: 'news',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Sonora Yogya',
    frequency: 97.4,
    city: 'Yogyakarta',
    genre: 'classic_hits',
    band: Band.fm,
  ),
  LocalStation(
    name: 'EMC Star FM',
    frequency: 97.8,
    city: 'Yogyakarta',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio GCD FM',
    frequency: 98.6,
    city: 'Yogyakarta',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Vedac FM',
    frequency: 99.0,
    city: 'Yogyakarta',
    genre: 'education',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Retjo Buntung',
    frequency: 99.4,
    city: 'Yogyakarta',
    genre: 'dangdut',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Swadesi Adhiloka',
    frequency: 99.9,
    city: 'Yogyakarta',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Nabawi Mulia',
    frequency: 100.2,
    city: 'Yogyakarta',
    genre: 'religious',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Impact PAS FM',
    frequency: 100.5,
    city: 'Yogyakarta',
    genre: 'religious',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Star Jogja FM',
    frequency: 101.3,
    city: 'Yogyakarta',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Swaragama FM',
    frequency: 101.7,
    city: 'Yogyakarta',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'RRI Pro 2 Yogyakarta',
    frequency: 102.5,
    city: 'Yogyakarta',
    genre: 'music',
    band: Band.fm,
  ),
  LocalStation(
    name: 'RRI Pro 3 Yogyakarta',
    frequency: 102.9,
    city: 'Yogyakarta',
    genre: 'news',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Delta FM Yogya',
    frequency: 103.7,
    city: 'Yogyakarta',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Ardhia FM',
    frequency: 104.1,
    city: 'Yogyakarta',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Unisi Radio',
    frequency: 104.5,
    city: 'Yogyakarta',
    genre: 'education',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Voks Radio Jogja',
    frequency: 105.3,
    city: 'Yogyakarta',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Petra FM',
    frequency: 105.7,
    city: 'Yogyakarta',
    genre: 'religious',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Geronimo',
    frequency: 106.1,
    city: 'Yogyakarta',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'RRI Pro 4 Yogyakarta',
    frequency: 106.6,
    city: 'Yogyakarta',
    genre: 'culture',
    band: Band.fm,
  ),
  LocalStation(
    name: 'KR Radio',
    frequency: 107.2,
    city: 'Yogyakarta',
    genre: 'news',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Suara Konco Tani',
    frequency: 711,
    city: 'Yogyakarta',
    genre: 'talk',
    band: Band.am,
  ),
  LocalStation(
    name: 'Radio Swara Kenanga',
    frequency: 783,
    city: 'Yogyakarta',
    genre: 'talk',
    band: Band.am,
  ),
  LocalStation(
    name: 'Radio Joss',
    frequency: 855,
    city: 'Yogyakarta',
    genre: 'talk',
    band: Band.am,
  ),
  LocalStation(
    name: 'RRI Yogyakarta Pro 4',
    frequency: 1107,
    city: 'Yogyakarta',
    genre: 'news',
    band: Band.am,
  ),
  LocalStation(
    name: 'Radio Muhammadiyah',
    frequency: 1395,
    city: 'Yogyakarta',
    genre: 'religious',
    band: Band.am,
  ),
];

// ── MEDAN ─────────────────────────────────────────────────────────────────────
// Source: AsiaWaves.net — FM partial to 91.6 MHz
const _medan = [
  LocalStation(
    name: 'La Femme',
    frequency: 88.0,
    city: 'Medan',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'RRI Medan Pro 4',
    frequency: 88.4,
    city: 'Medan',
    genre: 'news',
    band: Band.fm,
  ),
  LocalStation(
    name: 'RRI Medan Pro 3',
    frequency: 88.8,
    city: 'Medan',
    genre: 'news',
    band: Band.fm,
  ),
  LocalStation(
    name: 'P FM',
    frequency: 89.2,
    city: 'Medan',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'iSwara FM Medan',
    frequency: 89.6,
    city: 'Medan',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Hot 90 FM',
    frequency: 90.0,
    city: 'Medan',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Sonara',
    frequency: 90.4,
    city: 'Medan',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Mix FM',
    frequency: 90.8,
    city: 'Medan',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'M Radio',
    frequency: 91.6,
    city: 'Medan',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'RRI Pro 2 Medan',
    frequency: 92.4,
    city: 'Medan',
    genre: 'music',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Elshinta Medan',
    frequency: 93.2,
    city: 'Medan',
    genre: 'news',
    band: Band.fm,
  ),
  LocalStation(
    name: 'RRI Pro 1 Medan',
    frequency: 94.3,
    city: 'Medan',
    genre: 'news',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Suara Medan',
    frequency: 94.7,
    city: 'Medan',
    genre: 'dangdut',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Prapanca FM',
    frequency: 95.1,
    city: 'Medan',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio CB FM',
    frequency: 95.5,
    city: 'Medan',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'City Radio',
    frequency: 95.9,
    city: 'Medan',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Medan FM',
    frequency: 96.3,
    city: 'Medan',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Dangdut Indonesia Medan',
    frequency: 96.7,
    city: 'Medan',
    genre: 'dangdut',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Sikamoni',
    frequency: 97.1,
    city: 'Medan',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Prambors Medan',
    frequency: 97.5,
    city: 'Medan',
    genre: 'top40',
    band: Band.fm,
  ),
  LocalStation(
    name: 'I Radio Medan',
    frequency: 98.3,
    city: 'Medan',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Most FM Medan',
    frequency: 99.1,
    city: 'Medan',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Kardopa',
    frequency: 99.4,
    city: 'Medan',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Istana MBC',
    frequency: 99.9,
    city: 'Medan',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Smart FM Medan',
    frequency: 101.8,
    city: 'Medan',
    genre: 'news',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Bonsita',
    frequency: 102.2,
    city: 'Medan',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Best FM Medan',
    frequency: 103.0,
    city: 'Medan',
    genre: 'top40',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Simponi',
    frequency: 103.4,
    city: 'Medan',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'A Radio Medan',
    frequency: 103.8,
    city: 'Medan',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Maria Indonesia',
    frequency: 104.2,
    city: 'Medan',
    genre: 'religious',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio KISS FM Medan',
    frequency: 105.0,
    city: 'Medan',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Delta FM Medan',
    frequency: 105.8,
    city: 'Medan',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Sonya FM',
    frequency: 106.6,
    city: 'Medan',
    genre: 'pop',
    band: Band.fm,
  ),
  LocalStation(
    name: 'Radio Bethany',
    frequency: 900,
    city: 'Medan',
    genre: 'religious',
    band: Band.am,
  ),
];

// ── MASTER LIST ───────────────────────────────────────────────────────────────
// To add a new city: create a _cityName const list above and spread it here.
const List<LocalStation> allStations = [
  ..._jakarta,
  ..._surabaya,
  ..._semarang,
  ..._bandung,
  ..._yogyakarta,
  ..._medan,
];

// ── CITY COORDINATES ─────────────────────────────────────────────────────────
const Map<String, ({double lat, double lng})> cityCoordinates = {
  'Jakarta': (lat: -6.2088, lng: 106.8456),
  'Surabaya': (lat: -7.2575, lng: 112.7521),
  'Semarang': (lat: -6.9666, lng: 110.4196),
  'Bandung': (lat: -6.9175, lng: 107.6191),
  'Yogyakarta': (lat: -7.7956, lng: 110.3695),
  'Medan': (lat: 3.5952, lng: 98.6722),
  // TODO: add when verified — Makassar, Bali, Solo, Malang
};
